package ctxkey

const (
	HTTP_SERVER_APP_CONFIG     = CtxKey("HTTP_SERVER:APP_CONFIG")
	HTTP_SERVER_APP_DEPENDENCY = CtxKey("HTTP_SERVER:APP_DEPENDENCY")
	HTTP_SERVER_APP_REPOSITORY = CtxKey("HTTP_SERVER:APP_REPOSITORY")
	HTTP_SERVER_APP_SERVICE    = CtxKey("HTTP_SERVER:APP_SERVICE")
)
