package rediskey

// MASTER KEY
const (
	REDIS_KEY_EXAMPLE = "EXAMPLE"
)

// SECONDARY KEY
const (
	REDIS_KEY_EXAMPLE_CHILD_ONE = REDIS_KEY_EXAMPLE + ":CHILD:ONE"
	REDIS_KEY_EXAMPLE_CHILD_TWO = REDIS_KEY_EXAMPLE + ":CHILD:TWO"
)
